/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mechanicalSwitch.glb
Author: H11KB (https://sketchfab.com/H11KB)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yok-mint-holy-panda-mechanical-switch-model-a68ea354efad4d6ebfc1454cc3885202
Title: YOK mint holy panda mechanical switch model
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from "three";

export function MechanicalSwitch(props) {
  const { nodes, materials } = useGLTF('/models/mechanicalSwitch.glb')
  let camera = useThree(state => state.camera)
  const ref = useRef(null)
  const stemRef= useRef(null)

  useEffect(() =>{
    materials.housing.color.set('#2D2D2D')
    materials.stem.color.set('#13C612');
  },[])

  useFrame((state) =>{
    const t = state.clock.getElapsedTime()
    stemRef.current.position.y = (0.125 + Math.sin(t*6)) / 16
  })

  useLayoutEffect(() =>{
    camera.position.set(0, 1, 2)
    
  },[])

  return (
    <group {...props} dispose={null} ref={ref} >
      <mesh geometry={nodes.Object_4.geometry} material={materials.housing} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.stem} ref={stemRef}/>
      <mesh geometry={nodes.Object_6.geometry} material={materials.copper} />
    </group>
  )
}

useGLTF.preload('/models/mechanicalSwitch.glb')
